export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';
export const ADD_TO_FAVORITE_REQUEST = 'ADD_TO_FAVORITE_REQUEST';
export const ADD_TO_FAVORITE_SUCCESS = 'ADD_TO_FAVORITE_SUCCESS';
export const ADD_TO_FAVORITE_FAILURE = 'ADD_TO_FAVORITE_FAILURE';

export const GET_FAVORITE_LIST_REQUEST = 'GET_FAVORITE_LIST_REQUEST';
export const GET_FAVORITE_LIST_SUCCESS = 'GET_FAVORITE_LIST_SUCCESS';
export const GET_FAVORITE_LIST_FAILURE = 'GET_FAVORITE_LIST_FAILURE';
//  Product
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// Cart
export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
export const UPDATE_CART_ITEM_QTY = 'UPDATE_CART_ITEM_QTY';

// Checkout

export const UPDATE_CHECKOUT_PROGRESS = 'UPDATE_CHECKOUT_PROGRESS';
// User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
