export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT';
export const ADD_FAV_PRODUCT_REQUEST = 'ADD_FAV_PRODUCT_REQUEST';
export const ADD_FAV_PRODUCT_SUCCESS = 'ADD_FAV_PRODUCT_SUCCESS';
export const ADD_FAV_PRODUCT_FAILURE = 'ADD_FAV_PRODUCT_FAILURE';
export const ADD_FAV_SHOP = 'ADD_FAV_SHOP';
//  Product
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

// Cart
export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_CART_ITEM = 'ADD_CART_ITEM';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CLEAR_CART_ITEM = 'CLEAR_CART_ITEM';
